// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/note.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Note struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed            string               `protobuf:"bytes,3,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1ccfac48034b3a, []int{0}
}

func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (m *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(m, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetCompleted() string {
	if m != nil {
		return m.Completed
	}
	return ""
}

func (m *Note) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Note) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NoteReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteReq) Reset()         { *m = NoteReq{} }
func (m *NoteReq) String() string { return proto.CompactTextString(m) }
func (*NoteReq) ProtoMessage()    {}
func (*NoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1ccfac48034b3a, []int{1}
}

func (m *NoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteReq.Unmarshal(m, b)
}
func (m *NoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteReq.Marshal(b, m, deterministic)
}
func (m *NoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteReq.Merge(m, src)
}
func (m *NoteReq) XXX_Size() int {
	return xxx_messageInfo_NoteReq.Size(m)
}
func (m *NoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoteReq proto.InternalMessageInfo

func (m *NoteReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NoteReq) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type NoteFindReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoteFindReq) Reset()         { *m = NoteFindReq{} }
func (m *NoteFindReq) String() string { return proto.CompactTextString(m) }
func (*NoteFindReq) ProtoMessage()    {}
func (*NoteFindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f1ccfac48034b3a, []int{2}
}

func (m *NoteFindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoteFindReq.Unmarshal(m, b)
}
func (m *NoteFindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoteFindReq.Marshal(b, m, deterministic)
}
func (m *NoteFindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoteFindReq.Merge(m, src)
}
func (m *NoteFindReq) XXX_Size() int {
	return xxx_messageInfo_NoteFindReq.Size(m)
}
func (m *NoteFindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoteFindReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoteFindReq proto.InternalMessageInfo

func (m *NoteFindReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Note)(nil), "proto.Note")
	proto.RegisterType((*NoteReq)(nil), "proto.NoteReq")
	proto.RegisterType((*NoteFindReq)(nil), "proto.NoteFindReq")
}

func init() {
	proto.RegisterFile("proto/note.proto", fileDescriptor_5f1ccfac48034b3a)
}

var fileDescriptor_5f1ccfac48034b3a = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4b, 0x84, 0x50,
	0x10, 0xc6, 0x7b, 0xa6, 0x5b, 0x8e, 0xb0, 0xc4, 0xd0, 0x41, 0xa4, 0x48, 0xbc, 0x64, 0x17, 0x85,
	0xed, 0xd4, 0xa1, 0xc3, 0x12, 0x74, 0xec, 0x60, 0xdd, 0xc3, 0xf5, 0x4d, 0xcb, 0x03, 0xdd, 0x67,
	0x36, 0xdb, 0xdf, 0xd7, 0x9f, 0x16, 0xef, 0x3d, 0x65, 0x65, 0x21, 0x3a, 0xe9, 0x37, 0xf3, 0x7d,
	0x33, 0xbf, 0x79, 0x70, 0xd1, 0x0f, 0x9a, 0x75, 0xb9, 0xd3, 0x4c, 0x85, 0xfd, 0xc5, 0xc0, 0x7e,
	0x92, 0x9b, 0xad, 0xd6, 0xdb, 0x96, 0x4a, 0xab, 0x36, 0xfb, 0x8f, 0x92, 0x55, 0x47, 0x5f, 0x5c,
	0x77, 0xbd, 0xf3, 0x65, 0x3f, 0x02, 0xfc, 0x17, 0xcd, 0x84, 0x4b, 0xf0, 0x94, 0x8c, 0x45, 0x2a,
	0xf2, 0xa0, 0xf2, 0x94, 0xc4, 0x4b, 0x08, 0x58, 0x71, 0x4b, 0xb1, 0x97, 0x8a, 0x3c, 0xac, 0x9c,
	0xc0, 0x2b, 0x08, 0x1b, 0xdd, 0xf5, 0x2d, 0x31, 0xc9, 0xf8, 0xd4, 0x76, 0x0e, 0x05, 0x7c, 0x00,
	0x68, 0x06, 0xaa, 0x99, 0xe4, 0x7b, 0xcd, 0xb1, 0x9f, 0x8a, 0x3c, 0x5a, 0x25, 0x85, 0x43, 0x28,
	0x26, 0x84, 0xe2, 0x6d, 0x42, 0xa8, 0xc2, 0xd1, 0xbd, 0x66, 0x13, 0xdd, 0xf7, 0x72, 0x8a, 0x06,
	0xff, 0x47, 0x47, 0xf7, 0x9a, 0xb3, 0x47, 0x38, 0x33, 0x17, 0x54, 0xf4, 0x79, 0x80, 0x16, 0x7f,
	0x42, 0x9b, 0x73, 0xce, 0x67, 0xd0, 0xd9, 0x35, 0x44, 0x26, 0xfe, 0xac, 0x76, 0xd2, 0x8c, 0x38,
	0x7a, 0x87, 0x55, 0xed, 0xda, 0xaf, 0x34, 0x7c, 0xab, 0x86, 0xf0, 0x16, 0x16, 0x4f, 0x16, 0x1a,
	0x97, 0x0e, 0xab, 0x18, 0x77, 0x27, 0xd1, 0x4c, 0x67, 0x27, 0x78, 0x07, 0xbe, 0x19, 0x89, 0x38,
	0x2b, 0x8f, 0x3b, 0x8e, 0xac, 0x9b, 0x85, 0x55, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x3b, 0xa6, 0x8e, 0xc6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NoteServiceClient is the client API for NoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NoteServiceClient interface {
	Create(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*Note, error)
	Find(ctx context.Context, in *NoteFindReq, opts ...grpc.CallOption) (*Note, error)
}

type noteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteServiceClient(cc grpc.ClientConnInterface) NoteServiceClient {
	return &noteServiceClient{cc}
}

func (c *noteServiceClient) Create(ctx context.Context, in *NoteReq, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := c.cc.Invoke(ctx, "/proto.NoteService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteServiceClient) Find(ctx context.Context, in *NoteFindReq, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := c.cc.Invoke(ctx, "/proto.NoteService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteServiceServer is the server API for NoteService service.
type NoteServiceServer interface {
	Create(context.Context, *NoteReq) (*Note, error)
	Find(context.Context, *NoteFindReq) (*Note, error)
}

// UnimplementedNoteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNoteServiceServer struct {
}

func (*UnimplementedNoteServiceServer) Create(ctx context.Context, req *NoteReq) (*Note, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedNoteServiceServer) Find(ctx context.Context, req *NoteFindReq) (*Note, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterNoteServiceServer(s *grpc.Server, srv NoteServiceServer) {
	s.RegisterService(&_NoteService_serviceDesc, srv)
}

func _NoteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NoteService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Create(ctx, req.(*NoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteFindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NoteService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteServiceServer).Find(ctx, req.(*NoteFindReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NoteService",
	HandlerType: (*NoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NoteService_Create_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _NoteService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/note.proto",
}
